apiVersion: apps/v1
kind: Deployment
metadata:
  name: seb-exam-portal
  namespace: seb-exam-portal
  labels:
    app: seb-exam-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seb-exam-portal
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: seb-exam-portal
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000 # Critical: Forces Kubernetes to give ownership of the PVC storage to your appuser (UID 1000)
      containers:
        - name: seb-exam-portal
          image: rodas01/seb-exam-portal:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/data # Connects the PVC storage to your app's data folder
              name: exam-data-storage
          envFrom:
            - configMapRef:
                name: seb-portal-config
            - secretRef:
                name: seb-portal-secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: exam-data-storage
          persistentVolumeClaim:
            claimName: seb-exam-pvc # Links to the PVC we created above
