apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: seb-exam-portal-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: "seb-exam-portal"
      images:
        - alias: "portal-image"
          imageName: "rodas01/seb-exam-portal"
          commonUpdateSettings:
            updateStrategy: "semver"
            versionConstraint: ">=1.0.0"
            # EXPLICITLY ALLOW ONLY SEMVER TAGS (blocks :latest from being picked up)
            allowTags: "regexp:^v[0-9]+\.[0-9]+\.[0-9]+$"
            writeBackMethod: "git:secret:argocd/github-crets" # Ensure your git writeback has proper credentials