apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: seb-exam-portal
  namespace: seb-exam-portal
  labels:
    app: seb-exam-portal
  annotations:
    # Tells Image Updater which image alias to watch and write back changes for
    argocd-image-updater.argoproj.io/image-list: portal-image=rodas01/seb-exam-portal
    # Sets the update strategy to SemVer and restricts it to your version constraints
    argocd-image-updater.argoproj.io/portal-image.update-strategy: semver
    argocd-image-updater.argoproj.io/portal-image.allow-tags: regexp:^v[0-9]+\.[0-9]+\.[0-9]+$
spec:
  replicas: 5
  selector:
    matchLabels:
      app: seb-exam-portal
  template:
    metadata:
      labels:
        app: seb-exam-portal
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: seb-exam-portal
          # CHANGED from :latest to v1.0.0
          image: rodas01/seb-exam-portal:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/data
              name: exam-data-storage
          envFrom:
            - configMapRef:
                name: seb-portal-config
            - secretRef:
                name: seb-portal-secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: exam-data-storage
          persistentVolumeClaim:
            claimName: seb-exam-pvc
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 10m }
