apiVersion: v1
kind: Secret
metadata:
  name: seb-portal-secret
  namespace: seb-exam-portal
type: Opaque
stringData:
  SESSION_SECRET: "51a8e2f6068d57fefb194ef146af1329ae2554b18aa7c57cf3f8f3bb9ce0e8e7"
