apiVersion: v1
kind: Service
metadata:
  name: seb-portal-lb
  namespace: seb-exam-portal
  annotations:
    metallb.universe.tf/address-pool: lab-pool # Change from 'default' to 'lab-pool'
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.11 # Forces MetalLB to assign this specific IP
  selector:
    app: seb-exam-portal
  ports:
    - protocol: TCP
      port: 80 # External port accessible by IT staff
      targetPort: 80 # Internal container port
